language: ruby
sudo: false
rvm:
  - "1.9.3"
  - "2.3.0"
  - "jruby-19mode"  # JRuby in 1.9 mode
  - "rbx-2"

matrix:
  allow_failures:
    - rvm: rbx-2
cache: bundler
before_install:
  - gem update bundler
